apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  POSTGRES_HOST: host.minikube.internal
  POSTGRES_PORT: "5432"
  REDIS_HOST: host.minikube.internal
  REDIS_PORT: "6379"
