apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: nodejs-devops
data:
  POSTGRES_HOST: ecommerce-postgres.c7u8o4skoxo0.ap-south-1.rds.amazonaws.com
  POSTGRES_PORT: "5432"
  REDIS_HOST: ecommerce-redis.2wll9f.ng.0001.aps1.cache.amazonaws.com
  REDIS_PORT: "6379"
