apiVersion: v1
kind: Service
metadata:
  name: order-service-bg
  namespace: nodejs-devops
  labels:
    monitoring: order-service

spec:
  type: ClusterIP

  selector:
    app: order-service
    track: rolling

  ports:
    - name: http
      port: 8004
      targetPort: 8004
