apiVersion: v1
kind: Service
metadata:
  name: payment-service-bg
  namespace: nodejs-devops
spec:
  type: ClusterIP
  selector:
    app: payment-service
    version: blue
  ports:
    - port: 8005
      targetPort: 8005
