apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-service-monitor
  namespace: nodejs-devops
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      monitoring: payment-service
  namespaceSelector:
    matchNames:
      - nodejs-devops
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
