apiVersion: v1
kind: Service
metadata:
  name: product-service-bg
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: product-service
    version: blue
  ports:
    - port: 8002
      targetPort: 8002
