apiVersion: v1
kind: Service
metadata:
  name: user-service-bg
  namespace: nodejs-devops
  labels:
    monitoring: user-service

spec:
  type: ClusterIP

  selector:
    app: user-service
    track: rolling

  ports:
    - name: http
      port: 8001
      targetPort: 8001
